spring.application.name=ebank-backend
# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ebank_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT Configuration
jwt.secret=QUlNVklWR0hVUEpPVE5MSUZFV0lTSEJPRFVFTEJJWUtBQ0pZRUJPSFJXSU5PTEJVWUNBQ1JESlVRTkhFQUhPTA==
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=${MAIL_FROM:${GMAIL_USERNAME:}}

app.frontend.base-url=http://localhost:3000